In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

Read image and display

In [2]:
path_to_image = 'c:/Users/siddhant.dash/Downloads/klaus_hargreaves.jpg'
img = cv2.imread(path_to_image)

cv2.imshow('Frame_name',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Write image

In [43]:
path_to_image = 'c:/Users/siddhant.dash/Downloads/klaus_hargreaves.jpg'
img = cv2.imread(path_to_image)

cv2.imwrite('c:/Users/siddhant.dash/Downloads/klaus.jpg',img)

True

Atomic Info of an image

In [17]:
img.shape

(200, 200)

In [7]:
type(img)

numpy.ndarray

In [18]:
print(img)

[[ 84  84  84 ...  66  64  64]
 [ 84  84  83 ...  64  61  61]
 [ 84  84  83 ...  66  62  61]
 ...
 [ 34  35  35 ... 217 220 222]
 [ 36  37  36 ... 216 217 219]
 [ 36  37  37 ... 204 206 208]]


In [23]:

cv2.imshow('Cropped',img[0:120,60:150])
cv2.waitKey(0)
cv2.destroyAllWindows()

Drawing/writing on image

In [5]:
img1 = cv2.putText(img.copy(),'Klaus',(30,150),cv2.FONT_HERSHEY_SIMPLEX,1,(200,100,0),2,cv2.LINE_AA)
cv2.imshow('1',img1)
img2 = cv2.rectangle(img.copy(),(60,0),(150,120),(0,0,255),2)
cv2.imshow('2',img2)
img3 = cv2.circle(img.copy(),(80,80),30,(0,255,255),2)
cv2.imshow('3',img3)
img4 = cv2.line(img.copy(),(60,0),(150,120),(0,0,0),2)
cv2.imshow('4',img4)

cv2.waitKey(0)
cv2.destroyAllWindows()

Thresholding

In [4]:
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('gray',gray)

val1,th1 = cv2.threshold(gray,125,255,cv2.THRESH_BINARY)
cv2.imshow('t1',th1)

val2,th2 = cv2.threshold(gray,125,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imshow('t2',th2)

th3 = cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,155,1)
cv2.imshow('t3',th3)


cv2.waitKey(0)
cv2.destroyAllWindows()